name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore ./Faff.sln
    - name: Build
      run: dotnet build ./Faff.sln --no-restore
    - name: Test
      run: dotnet test ./test/Faff.Tests.csproj      
    - run: echo "🍏 This job's status is ${{ job.status }}."
